site_name: ESIR2 - Remote English

site_url: https://lethargii.github.io/ESIR2-RemoteEnglish/

repo_url: https://github.com/lethargii/ESIR2-RemoteEnglish

theme:
  name: material
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: blue grey
      accent: blue grey

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: blue grey
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.footer
  icon:
    repo: fontawesome/brands/github


markdown_extensions:
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:l.sevault@proton.me
    - icon: fontawesome/brands/github
      link: https://github.com/lethargii/ESIR2-RemoteEnglish

copyright: Copyright &copy; 2026 Lucien Sevault Wolber
